"""Phase 1 data audit: dataset stats, detector scores, flags, and length-confound checks.

Usage:
    python -m curation.audit [SOURCE ...] --out OUT_DIR

Writes OUT_DIR/scores.parquet (one row per episode) and OUT_DIR/audit.md.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

from curation.datasets import BY_NAME, SOURCES, download_tabular
from curation.detectors import score_dataset
from curation.load import load_dataset, find_datasets

# Initial thresholds; to be recalibrated against hand labels (curation/label_tool).
IDLE_S = 3.0  # >3 s motionless at start or end (seconds, not fraction: fractions are length-confounded)
TRUNCATION = 1.0  # still moving at >= median moving speed just before the end
SPIKE = 10.0  # one step >10x the episode's median moving speed: recording glitch
JERK_MAD_Z = 3.5  # robust z-score of jerk within the source
MIN_LEN = 10


def robust_z(x: pd.Series) -> pd.Series:
    med = x.median()
    mad = (x - med).abs().median() * 1.4826 + 1e-8
    return (x - med) / mad


def score_source(name: str) -> pd.DataFrame:
    src = BY_NAME[name]
    root = download_tabular(src)
    rows = []
    for ds_root in find_datasets(root):
        subset = str(ds_root.relative_to(root)) if ds_root != root else ""
        eps = [e for e in load_dataset(ds_root, name, subset) if e.length >= MIN_LEN]
        if eps:
            # Normalize per sub-dataset: community datasets differ in calibration and fps.
            for r in score_dataset(eps):
                r["robot"] = src.robot
                r["action_dim"] = eps[0].action.shape[1]
                r["state_dim"] = 0 if eps[0].state is None else eps[0].state.shape[1]
                rows.append(r)
    return pd.DataFrame(rows)


def add_flags(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["jerk_z"] = df.groupby("source")["jerk"].transform(robust_z)
    df["flag_idle"] = (df["idle_start_s"] > IDLE_S) | (df["idle_end_s"] > IDLE_S)
    df["flag_truncation"] = df["truncation"] > TRUNCATION
    df["flag_spike"] = df["spike"] > SPIKE
    df["flag_flailing"] = df["jerk_z"] > JERK_MAD_Z
    df["flag_any"] = df[FLAGS[:-1]].any(axis=1)
    return df


FLAGS = ["flag_idle", "flag_truncation", "flag_spike", "flag_flailing", "flag_any"]
SCORES = ["idle_start_s", "idle_end_s", "idle_start_frac", "truncation", "spike", "jerk"]


def length_confound(df: pd.DataFrame, score_cols: list[str]) -> pd.DataFrame:
    """Spearman rho of each score vs episode length, overall and within length quintiles.

    A detector whose signal is mostly length shows a large overall rho and much
    weaker variation once length is held roughly fixed.
    """
    out = []
    for source, g in df.groupby("source"):
        q = pd.qcut(g["length"].rank(method="first"), 5, labels=False)
        for col in score_cols:
            rho = spearmanr(g[col], g["length"]).statistic
            within = [spearmanr(gg[col], gg["length"]).statistic for _, gg in g.groupby(q) if len(gg) > 10]
            # how much the score still varies within a length bin vs overall
            spread_ratio = float(np.nanmean([gg[col].std() for _, gg in g.groupby(q)]) / (g[col].std() + 1e-12))
            out.append(dict(source=source, score=col, rho_length=rho,
                            mean_rho_within_quintile=float(np.nanmean(within)) if within else np.nan,
                            within_bin_spread_ratio=spread_ratio))
    return pd.DataFrame(out)


def dataset_stats(df: pd.DataFrame) -> pd.DataFrame:
    g = df.groupby("source")
    return pd.DataFrame({
        "robot": g["robot"].first(),
        "sub_datasets": g["subset"].nunique(),
        "episodes": g.size(),
        "frames": g["length"].sum(),
        "fps": g["fps"].agg(lambda s: "/".join(str(int(v)) for v in sorted(s.unique()))),
        "len_median_s": g["duration_s"].median().round(1),
        "len_p5_s": g["duration_s"].quantile(0.05).round(1),
        "len_p95_s": g["duration_s"].quantile(0.95).round(1),
        "action_dim": g["action_dim"].agg(lambda s: "/".join(str(v) for v in sorted(s.unique()))),
        "tasks": g["task"].nunique(),
        "success_labels": g["success_label"].agg(lambda s: f"{s.notna().mean():.0%}"),
    }).reindex([s.name for s in SOURCES if s.name in g.groups])


def flag_rates(df: pd.DataFrame) -> pd.DataFrame:
    return (df.groupby("source")[FLAGS].mean() * 100).round(1).reindex([s.name for s in SOURCES if s.name in df["source"].unique()])


def write_report(df: pd.DataFrame, out: Path) -> None:
    scores = SCORES
    lines =["# Phase 1 data audit", "", "Generated by `python -m curation.audit`. Thresholds are initial and"
             " will be recalibrated against hand labels.", ""]
    lines += ["## Dataset stats", "", dataset_stats(df).to_markdown(), ""]
    lines += ["## Flag rates (% of episodes)", "",
              f"idle: >{IDLE_S:g} s motionless at start or end; truncation: median speed over the final 5% "
              f"(excluding the last frame) ≥ {TRUNCATION}× median moving speed; spike: one step > {SPIKE:g}× "
              f"median moving speed; flailing: jerk robust-z > {JERK_MAD_Z} within source.", "",
              flag_rates(df).to_markdown(), ""]
    lines += ["## Length confound", "",
              "Spearman ρ of each raw score with episode length, overall and averaged within length quintiles. "
              "`within_bin_spread_ratio` near 1 means the score varies as much among similar-length episodes "
              "as overall (good); near 0 means it is mostly length.", "",
              length_confound(df, scores).round(3).to_markdown(index=False), ""]
    (out / "audit.md").write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("names", nargs="*", default=[s.name for s in SOURCES])
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    df = add_flags(pd.concat([score_source(n) for n in args.names], ignore_index=True))
    df.to_parquet(args.out / "scores.parquet")
    write_report(df, args.out)
    print((args.out / "audit.md").read_text())


if __name__ == "__main__":
    main()
